# Generated by Django 5.0.6 on 2024-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('sage', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
